[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
# Skip "Module level import not at top of file"
ignore = ["E402"]

[tool.ruff.format]
quote-style = "single"
